### ISSUE TITLE
invoke-method hangs on returned file descriptor

### ISSUE THREAD

**Issue by eadmund** [death/dbus#13]
This succeeds:

    (with-open-bus (bus (system-server-addresses))
            (with-introspected-object (logind bus "/org/freedesktop/login1" "org.freedesktop.login1")
              (logind "org.freedesktop.login1.Manager" "ListInhibitors")))

but this hangs, apparently forever:

    (with-open-bus (bus (system-server-addresses))
            (with-introspected-object (logind bus "/org/freedesktop/login1" "org.freedesktop.login1")
              (logind "org.freedesktop.login1.Manager" "Inhibit" "sleep" "test" "testing" "delay")))

I _think_ it's because Inhibit returns a file descriptor. I've not been able to come up with a fix; can you please take a look and see if you can reproduce it?

**Comment by death** [comment]
I managed to reproduce it, and I am in the process of figuring it out by looking into the behavior of the dbus-send tool (which does not block). For now I assert that the invocation message is encoded equivalently by both this library and dbus-send. I am going on vacation, so further progress may come slow... Maybe you can follow this line of investigation and see where it goes.
