### ISSUE TITLE
Defining methods with no return value

### ISSUE THREAD

**Issue by Ambrevar** [death/dbus#22]
With D-Bus methods may have no return values (which means in particular that the caller won't be waiting).

I'm wondering how to this with this library.  It seems that setting the return-types to `()` in `dbus:define-dbus-method` does not work, a condition is raised:

```
Method handler (NEXT::CORE-OBJECT NEXT::request-resource) returned bad results; expected-signature=NIL, results=(nil).
```

**Comment by death** [comment]
`NIL` is a value. If you want to return no values, use `(VALUES)`.

**Comment by Ambrevar** [comment]
Makes sense, thanks!
