### ISSUE TITLE
Licensing issue in xmlspam dependency

### ISSUE THREAD

**Issue by Ambrevar** [death/dbus#25]
cl-xmlspam does not have any license and this dbus library depends on it, which means that it cannot be distributed as free software :(
I've opened a issue on https://github.com/defunkydrummer/cl-xmlspam/issues/1 and I've contacted the original author, Rog Peppe, still waiting for an answer :)

Should this remain unresolve, @death do you have a plan to work around the licensing issue?

**Comment by death** [comment]
This (dbus) library is a personal project, most of which was hacked some 9 years ago. I no longer use dbus, so have no plans to work on it further.  That said, I may accept patches for it.

**Comment by Ambrevar** [comment]
Upstream is now licensed!  Hooray! https://github.com/rogpeppe/cl-xmlspam
